services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
      - Smtp__Host=${Smtp__Host}
      - Smtp__Port=${Smtp__Port}
      - Smtp__User=${Smtp__User}
      - Smtp__Pass=${Smtp__Pass}
      - Smtp__From=${Smtp__From}
      - Jwt__Key=${Jwt__Key}
      - Frontend__Url=${Frontend__Url}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
